# This is the name of the GitHub Action
name: Generate Contribution Snake

# This controls when the action will run
on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Also runs on every push to the main branch
  push:
    branches:
      - main

# The sequence of tasks to perform
jobs:
  generate:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu
    steps:
      # Step 1: Check out the repository, so the action can access your files
      - uses: actions/checkout@v3

      # Step 2: This is where your code snippet goes!
      # It generates the snake animations.
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # Your GitHub username is automatically fetched
          github_user_name: ${{ github.repository_owner }}

          # The list of output files to generate with different styles
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      # Step 3: Commit the generated files back into your repository
      # This pushes the generated SVG and GIF files to a branch named "output"
      - name: Push generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

